### PR TITLE
feat(SPV-869): changed global to globalThis

### PR DESCRIPTION
**Pull request by Nazarii-4chain**
# Pull Request Checklist

- [ ] 📖 I created my PR using provided  : [CODE_STANDARDS](https://github.com/bitcoin-sv/spv-wallet-js-client/blob/main/.github/CODE_STANDARDS.md)
- [ ] 📖 I have read the short Code of Conduct: [CODE_OF_CONDUCT](https://github.com/bitcoin-sv/spv-wallet-js-client/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] 🏠 I tested my changes locally.
- [ ] ✅ I have provided tests for my changes.
- [ ] 📝 I have used conventional commits.
- [ ] 📗 I have updated any related documentation.
- [ ] 💾 PR was issued based on the Github or Jira issue.

### CODE REVIEW

**Review by chris-4chain — APPROVED** [review]
Please confirm if it works on node.js and on web app.

**Comment by Nazarii-4chain** [comment]
> Please confirm if it works on node.js and on web app.

Work for node.js either

**Review by chris-4chain — CHANGES_REQUESTED** [review]
Please bump version in `package.json` from `"version": "1.0.0-beta.7",` to `"version": "1.0.0-beta.8",`.

That will simplify a process of releasing a new version after merge.

**Comment by Nazarii-4chain** [comment]
> Please bump version in `package.json` from `"version": "1.0.0-beta.7",` to `"version": "1.0.0-beta.8",`.
> 
> That will simplify a process of releasing a new version after merge.

Changed

**Review by chris-4chain — APPROVED** [review]

**Pull request merged**
